### ISSUE TITLE
error: type 'Device' has no member 'defaultXLA'

### ISSUE THREAD

**Issue by kushukla** [tensorflow/swift-models#475]
Hi,

For some reason `swift build` is failing for me with an error message `error: type 'Device' has no member 'defaultXLA'`. Is there anything that I am missing out?

**Verify Swift toolchain**
```console
Projects kunal$ export PATH=/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-04-17-a.xctoolchain/usr/bin:"${PATH}"
Projects kunal$ which swift
/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-04-17-a.xctoolchain/usr/bin/swift
```

**Git Clone**
```console
Projects kunal$ git clone https://github.com/tensorflow/swift-models.git
Cloning into 'swift-models'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 3329 (delta 21), reused 27 (delta 10), pack-reused 3276
Receiving objects: 100% (3329/3329), 37.72 MiB | 2.76 MiB/s, done.
Resolving deltas: 100% (1902/1902), done.
```

**Build**
```console
Projects kunal$ cd swift-models/
swift-models kunal$ swift build
Fetching https://github.com/apple/swift-protobuf.git
Fetching https://github.com/apple/swift-argument-parser
Cloning https://github.com/apple/swift-argument-parser
Resolving https://github.com/apple/swift-argument-parser at 0.0.2
Cloning https://github.com/apple/swift-protobuf.git
Resolving https://github.com/apple/swift-protobuf.git at 1.7.0
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:193:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/Users/kunal/Documents/Projects/swift-models/Benchmarks/Models/ImageClassificationInference.swift:58:36: error: type 'Device' has no member 'defaultXLA'
        case .x10: device = Device.defaultXLA
                            ~~~~~~ ^~~~~~~~~~
/Users/kunal/Documents/Projects/swift-models/Benchmarks/Models/ImageClassificationInference.swift:77:17: error: use of unresolved identifier 'LazyTensorBarrier'
                LazyTensorBarrier()
                ^~~~~~~~~~~~~~~~~
/Users/kunal/Documents/Projects/swift-models/Benchmarks/Models/ImageClassificationTraining.swift:52:36: error: type 'Device' has no member 'defaultXLA'
        case .x10: device = Device.defaultXLA
                            ~~~~~~ ^~~~~~~~~~
/Users/kunal/Documents/Projects/swift-models/Benchmarks/Models/ImageClassificationTraining.swift:92:17: error: use of unresolved identifier 'LazyTensorBarrier'
                LazyTensorBarrier()
                ^~~~~~~~~~~~~~~~~
[277/296] Linking DCGAN
swift-models kunal$ 
```
Thanks,
Kunal

**Comment by shabalind** [comment]
Hi @kushukla, swift-models code is being reworked to adapt to new APIs coming in the upcoming 0.9 release. As a potential short-term solution you can use the swift-models code from `tensorflow-0.8` branch. It is known to work with the released 0.8 toolchain.

**Comment by kushukla** [comment]
worked like a charm. Thanks! @shabalind

**Comment by BradLarson** [comment]
Also, we should have a macOS nightly toolchain up today or tomorrow that has this new interface in it. The macOS builds ran into some problems for a bit, but those have largely been resolved. Once that new nightly toolchain is up, you should be able to resume using the head of swift-models with it.

**Comment by kushukla** [comment]
Thanks! @BradLarson, looking for to the nightly toolchain
