### PR TITLE
docs: update build docs for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Windows snapshots as of 10/28 have SwiftPM in the snapshots and works
to build the models.  Update the docs for build instructions.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -29,13 +29,25 @@ swift test
 
 ### Windows
```
Comment (texasmichelle) [inline README.md:31]: How about adding a note that this only works with the 0.12 RC?

File: README.md [hunk 2]
```diff
@@ -29,13 +29,25 @@ swift test
...
+#### Build
+
+```cmd
+swift build -Xswiftc -use-ld=lld -c release
+```
+
+#### Test
+
+```cmd
+swift test -Xswiftc -use-ld=lld -c release
```
[the remark this answers is not in the document]
Comment (texasmichelle) [reply README.md:41]: This command doesn't actually succeed (I get duplicate symbol errors), so it would be good to add fixes or a note here.

**Review by texasmichelle — APPROVED** [review]
Combining the copy commands in https://github.com/tensorflow/swift-models/tree/master/Examples/GPT2-Inference#run would round out these updates 👍

File: README.md (hunk 1 above)
Comment (compnerd) [reply README.md:31]: It works with the currently linked snapshot as well, so I think that this is accurate as is.

**Comment by compnerd** [comment]
Yes, I will try to update the other instructions in a follow up change.
